site_name: vulnproof
theme:
    logo: assets/logo2.png
    favicon: images/favicon.ico
    features:
        - navigation.top
        - search.share
    icon:
        admonition:
            note: octicons/tag-16
            abstract: octicons/checklist-16
            info: octicons/info-16
            tip: octicons/squirrel-16
            success: octicons/check-16
            question: octicons/question-16
            warning: octicons/alert-16
            failure: octicons/x-circle-16
            danger: octicons/zap-16
            bug: octicons/bug-16
            example: octicons/beaker-16
            quote: octicons/quote-16
    name: material
    palette:
        primary: black
        scheme: slate
    font:
        text: Maven Pro
markdown_extensions:
    - attr_list
    - md_in_html
    - toc:
          permalink: 🔗
          permalink_title: Anchor link to this section for reference
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.mark
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - def_list
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
    - Welcome: index.md
    - About: About.md
    - Getting Started: Getting-Started.md
    - Authentication:
          - User ID & Password: Authentication/UserID-Passwords.md
          - MFA:
                - Authentication/MFA/Authenticator-Management.md
                - Authentication/MFA/Types.md
extra:
    analytics:
        provider: google
        property: G-17ZERL41HS
    generator: false
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/vulnproof
        - icon: fontawesome/brands/youtube
          link: https://www.youtube.com/@vulnproof
        - icon: fontawesome/brands/discord
          link: https://discord.gg/H4Fqh8GJMn
copyright: Copyright &copy; 2022 vulnproof
extra_css:
    - stylesheets/extra.css
